models:
  default:
    name: "GPT-3.5"
    provider: "openai"
    model_name: "gpt-3.5-turbo"
    base_url: "https://api.openai.com/v1"
    api_key: "${OPENAI_API_KEY}"
    default_params:
      temperature: 0.7
      max_tokens: 1000
      top_p: 1.0
  
  deepseek:
    name: "DeepSeek"
    provider: "deepseek"
    model_name: "deepseek-chat"
    base_url: "https://api.deepseek.com/v1"
    api_key: "${DEEPSEEK_API_KEY}"
    default_params:
      temperature: 0.7
      max_tokens: 1000
      top_p: 1.0

prompt_templates:
  - id: "general_question"
    title: "一般问题"
    content: "请回答以下问题: {{input}}"
  
  - id: "analysis"
    title: "分析报告"
    content: "请对以下内容进行深入分析，包括优缺点、潜在风险和改进建议: {{input}}"
  
  - id: "summary"
    title: "内容总结"
    content: "请将以下内容概括为简洁的要点: {{input}}"

# 全局设置
settings:
  logging:
    level: "INFO"
    file: "logs/llm_api.log"
    max_size: "10MB"
    backups: 3
  
  server:
    port: 8000
    host: "0.0.0.0"
    debug: true
    cors_origins: ["*"]

codeIndexing:
  enabled: true
  scanOptions:
    ignoreDirs: [".git", "node_modules", "dist", "build"]
    fileExtensions: [".js", ".ts", ".jsx", ".tsx", ".py", ".java"]
  indexingFrequency: "daily"